@url = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmIwM2I2YjRmMjNkYjY2YTg1MDYyYmIiLCJpYXQiOjE2NTgzMTIyNjl9.18mxP35q6IJUhszVSsS9QvfC7Eg1PxWYf3RjgPkKeMg
POST {{url}}/api/v1/user/signup
Content-Type: application/json

{
    "firstName": "John",    
    "lastName": "Peter",
    "email": "peter5@gmail.com",
    "password": "12345678",
    "password2": "12345678"
    
}

###

POST {{url}}/api/v1/user/login 
Content-Type: application/json

{
    "email": "pawan@gmail.com",
    "password": "123@Hello"
}
   
            
###
POST {{url}}/api/v1/user/logout
Authorization: Bearer {{token}}
Content-Type: application/json

###
POST {{url}}/api/v1/user/me/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data boundary=MyBoundary


### 
GET {{url}}/api/v1/user/me/62b03b6b4f23db66a85062bb/avatar
Authorization: Bearer {{token}}

###
GET {{url}}/api/v1/user/users
Content-Type: application/json